"""
generate_matlab_appendix.py

Scans a local folder recursively for .m files and generates a
matlab_appendix.tex file using the listings + matlab-prettifier packages.

Usage:
    python generate_matlab_appendix.py <matlab_root_folder> <output_tex_file>

Example:
    python generate_matlab_appendix.py "C:/Projects/MyMatlab" "matlab_appendix.tex"

Then in your main.tex, add at the end:
    \\input{matlab_appendix}
"""

import os
import sys
import argparse
from pathlib import Path


LATEX_SPECIAL_CHARS = str.maketrans({
    "_": r"\_",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
})


def escape_latex(text: str) -> str:
    return text.translate(LATEX_SPECIAL_CHARS)


def find_m_files(root: Path) -> list[Path]:
    """Recursively find all .m files, sorted by relative path."""
    return sorted(root.rglob("*.m"))


def generate_appendix(matlab_root: Path, output_path: Path):
    m_files = find_m_files(matlab_root)

    if not m_files:
        print(f"No .m files found under: {matlab_root}")
        sys.exit(1)

    print(f"Found {len(m_files)} .m file(s). Generating {output_path.name}...")

    lines = []

    # Header comment
    lines.append("% Auto-generated by generate_matlab_appendix.py")
    lines.append("% Do not edit manually — re-run the script to update.")
    lines.append("")

    # Required packages reminder (commented out — user adds to preamble)
    lines.append("% Ensure these are in your preamble:")
    lines.append("%   \\usepackage{listings}")
    lines.append("%   \\usepackage[T1]{fontenc}")
    lines.append("%   \\usepackage{matlab-prettifier}")
    lines.append("")

    for m_file in m_files:
        rel_path = m_file.relative_to(matlab_root)
        caption = escape_latex(str(rel_path))
        label = "lst:" + str(rel_path).replace("\\", "/").replace("/", "_").replace(".m", "").replace(" ", "_")

        lines.append(f"% --- {rel_path} ---")
        lines.append(r"\lstinputlisting[")
        lines.append(r"  style=Matlab-editor,")
        lines.append(r"  basicstyle=\mlttfamily\small,")
        lines.append(f"  caption={{\\texttt{{{caption}}}}},")
        lines.append(f"  label={{{label}}}")
        lines.append(f"]{{{m_file.as_posix()}}}") 
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Done! Written to: {output_path}")
    print()
    print("Add this to the end of your main.tex:")
    print(f"  \\input{{{output_path.stem}}}")


def main():
    parser = argparse.ArgumentParser(description="Generate a LaTeX appendix from .m files.")
    parser.add_argument("matlab_root", help="Root folder to scan for .m files")
    parser.add_argument(
        "output",
        nargs="?",
        default="matlab_appendix.tex",
        help="Output .tex file (default: matlab_appendix.tex)"
    )
    args = parser.parse_args()

    matlab_root = Path(args.matlab_root).resolve()
    output_path = Path(args.output).resolve()

    if not matlab_root.exists():
        print(f"Error: folder not found: {matlab_root}")
        sys.exit(1)

    generate_appendix(matlab_root, output_path)


if __name__ == "__main__":
    main()
